steps:
  # Copy the DAG files to the Google Cloud Storage bucket used by Composer
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args: ['-m', 'cp', '-r', './dags/', 'gs://$_COMPOSER_BUCKET/']

  # Optional: Update environment PyPI packages if necessary
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud composer environments update $_COMPOSER_ENV_NAME \
        --update-pypi-packages=python-dotenv \
        --location $_LOCATION

timeout: '1200s'  
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  

substitutions:
  _COMPOSER_BUCKET: ''
  _COMPOSER_ENV_NAME: ''
  _LOCATION: ''
