steps:
  # Copy the DAG files to the Google Cloud Storage bucket used by Composer
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args: ['-m', 'cp', '-r', './dags/', 'gs://$_COMPOSER_BUCKET/']

  # Update environment PyPI packages from requirements.txt
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Read requirements.txt and format it as a comma-separated list of packages
        PACKAGES=$(awk '{print $1}' requirements.txt | paste -sd "," -)
        
        # Update the Composer environment with the packages
        gcloud composer environments update ${_COMPOSER_ENV_NAME} \
        --update-pypi-packages=$PACKAGES \
        --location ${_LOCATION}

timeout: '1200s'  
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  

substitutions:
  _COMPOSER_BUCKET: '$_COMPOSER_BUCKET'
  _COMPOSER_ENV_NAME: '$_COMPOSER_ENV_NAME'
  _LOCATION: '$_LOCATION'
