name: Python application test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # Checks out the repository under $GITHUB_WORKSPACE, so your workflow can access it

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          # Sets up the specified version of Python

      # Adding Caching (Optional Enhancement)
      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
          # Installs pip packages from a requirements file if it exists

      - name: Set up Airflow Environment
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow
          airflow db init
      - name: Run unittests
        run: python -m unittest discover -s ./tests/
        # Executes the unittest discovery mode to find and run tests
